### ISSUE TITLE
UrlMappingMatchInfo not compatible with new aiohttp

### ISSUE THREAD

**Issue by kordsmi** [aamalev/aiohttp_apiset#11]
UrlMappingMatchInfo in compat.py not compatible with new aiohttp.
In new aiohttp problem with current_app were resolved.

**Comment by aamalev** [comment]
@kordsmi thanx
fixed in version 0.7.4

**Comment by kordsmi** [comment]
May be this class exclude from aiohttp_apiset?

**Comment by aamalev** [comment]
aiohttp.web_urldispatcher is not part of the public api. aiohttp.abc is public
