### ISSUE TITLE
'parameters' key on a Path Item object is not supported 

### ISSUE THREAD

**Issue by pbasista** [aamalev/aiohttp_apiset#14]
When using an OpenAPI v2 specification, which has the `parameters` key set on a Path Item object, this exception:
```
TypeError: pop() takes at most 1 argument (2 given)
```
is raised on this line:
https://github.com/aamalev/aiohttp_apiset/blob/130513201079d524c0b31c65f8d8f4fea2bfb776/aiohttp_apiset/swagger/router.py#L185

I think the problem is that the implementation assumes that the keys in the Path Item objects all hold the Operation Objects. However, the specification:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject
mentions that there can be a `parameters` key, which has a different type (a list). When encountered, it causes the mentioned exception to be raised.

**Comment by aamalev** [comment]
@pbasista thanx. fixed
https://github.com/aamalev/aiohttp_apiset/commit/cba5739d02c113c05c40566b263dc0b927946ee2
