### ISSUE TITLE
Strict validation for query params

### ISSUE THREAD

**Issue by Puzanovim** [aamalev/aiohttp_apiset#158]
Couldn't find how to set strict validation for unnecessary query parameters.
I assume it is important opportunity to get exception when unexpected params (not defined in the swagger spec) was given

**Comment by aamalev** [comment]
In general, the query can be set:
* marketing parameters such as utm_*
* browser cache suppressor
* parameters for routing
* other parameters for the access log

Thus, there is little benefit from such validation

**Comment by spinenkoia** [comment]
Can I do it optionally ?

**Comment by spinenkoia** [comment]
@aamalev ?

**Comment by aamalev** [comment]
> Can I do it optionally ?

The option should be disabled by default

**Comment by spinenkoia** [comment]
Yes, of course

**Comment by spinenkoia** [comment]
let 's close the task ?
