### ISSUE TITLE
Improvements suggestions [RU]

### ISSUE THREAD

**Issue by hh-h** [aamalev/aiohttp_apiset#25]
Привет, накидали список того, что нас интересует (читай, что мы готовы сами добавить)

Пользуемся мы исключительно через документирование хендлеров, без yml схем

1) Добавить новые типы в POST
У нас есть несколько запросов без тела (text/plain) и мы заливаем csv (text/csv) файлы (например), а они не поддерживаются
Решение: добавить новые кортежи для разных типов (.read, .post, .json)
например
```
POSTS = (
'application/x-www-form-urlencoded',
'multipart/form-data',
'text/plain'
)
READS = (
'application/octet-stream',
'text/csv'
)
if request.content_type in POSTS:
  body = yield from requests.post()
```

2) Скрыть роуты, которые добавляет apiset сам в [default]
```
GET /swagger/swagger.yaml
GET /swagger/
GET /swagger/{filename}
```
Решение: добавлять каким-нить кастомным роутом, который не попадет в аписет?

3) Добавить возможность указать yml файл с definition'ами, при использовании через док стринги.
Решение: новый флаг для конструктора, default = None, выдавать ошибку если задан path или просто игнорировать файл

Thoughts?

**Comment by aamalev** [comment]
Схему инклюдить нужно только если хочешь задать метаописание. definitions присутствовать могут, но не обязательно, т.к. ищутся они через механизм loader'a по указанным каталогам и они могут быть разбросаны по файлам.

В OpenAPI 3.0 более однозначно можно задать конвертацию типов входных параметров. Возможно гибридный подход с поддержкой 3+2 будет оптимален, надо экспериментировать.

**Comment by hh-h** [comment]
2) Разобрались косяк был у нас. В разделе default появляются роуты /doc/ doc/filename doc/swagger.yaml если создаешь роутер вот так `SwaggerRouter(swagger_ui='/api/v1/doc/')`, что неправильно делать, сделали `/docs/` - все ок.

3) Очень странно работает функционал, например создаю файл spec.yaml и кладу туда
```
swagger: "2.0"

info:
  title: TITLE
  version: 1.0.0

basePath: /api/v1

schemes:
  - http
  - https
```
дальше создаю файл `test.yaml` и кладу туда definitions:
```
definitions:
  TestInput:
    type: object
    required:
      - id
    properties:
       id:
        type: integer
```
main.py
```
router = SwaggerRouter(
    swagger_ui='/docs/',
    version_ui=3,
    search_dirs=[BASE],
)
router.add_post('/api/v1/doc/{doc_id:\d+}', handler='handlers.set_document')
router.include(spec='spec.yaml')
```
в UI получаю вот такую штуку
```
Errors
Hide
Resolver error at paths./doc/{doc_id}.post.parameters.1.schema.$ref
Could not resolve reference because of: Not Found
Resolver error at paths./doc/{doc_id}.post.responses.200.schema.items.$ref
Could not resolve reference because of: Not Found
```

если ссылаться вот так `spec.yaml#/definitions/TestInput` , получаю ошибку
```
  File "/aiohttp_apiset/swagger/loader.py", line 132, in factory
    return f(data['$ref'])
  File "/aiohttp_apiset/swagger/loader.py", line 512, in __call__
    return f('#' + rel_path)
  File "/aiohttp_apiset/swagger/loader.py", line 257, in __call__
    raise KeyError(item, str(self._path))
KeyError: ('#/definitions/TestInput', 'spec.yaml')
```

если вот так `#/definitions/TestInput`
```
  File "/aiohttp_apiset/swagger/loader.py", line 139, in __getitem__
    return self.factory(self._file, self._data[key])
  File "/aiohttp_apiset/swagger/loader.py", line 132, in factory
    return f(data['$ref'])
  File "/aiohttp_apiset/swagger/loader.py", line 510, in __call__
    path, rel_path = ref.split('#', 1)
AttributeError: 'NoneType' object has no attribute 'split'
```

пока запихал все в один файл `swagger.yaml` он должен быть именно `swagger.yaml` и ссылаюсь через `$ref: swagger.yaml#/definitions/TestInput` так и только так работает

4) можешь бапмнуть версию в pypi?

**Comment by aamalev** [comment]
@hh-h я сюда неотписался, но сейчас есть альфа-версия в которой есть фиксы твоей проблемы, есть ли желание её погонять?

**Comment by hh-h** [comment]
Привет! Да, я слежу за коммитами, пробовали уже из мастера либу, она, кстати, плохо собирается из гита :) У нас больше проблема теперь с тем, что сваггера больше недостаточно, нужны возможности OpenAPI3, так что начал писать свой валидатор для OAS3, может что-нибудь и получится

**Comment by aamalev** [comment]
Привет. Из гита незнаю, но есть пререлиз 0.10a2
